// Whether the rules path and the model path format each class's cases the same way.

/// Per formatting class, the cases the rules alone pass against the cases the shipped model path passes.
struct FormattingParity: Sendable, Equatable {
    /// What both paths wrote for one case; a refused model answer falls back to the rules, as the router does.
    struct Outputs: Sendable, Equatable {
        let rules: String
        /// The model path's finished text, or nil when its guards refused the answer.
        let model: String?

        init(rules: String, model: String?) {
            self.rules = rules
            self.model = model
        }

        /// What the person gets when the model path runs: its text, or the rules' when the model refuses.
        var delivered: String { model ?? rules }
    }

    /// One class's row: its cases split by which path passes them.
    struct Row: Sendable, Equatable {
        let formattingClass: FormattingClass
        let caseIDs: [String]
        /// Cases only the model path passes: speech that formats differently when the model is refused or late.
        let onlyModel: [String]
        /// Cases only the rules pass: the model path, right answer and all, breaks what the rules got right.
        let onlyRules: [String]
        /// Cases whose model answer the guards refused, so the rules' text stood.
        let refused: [String]
        /// Cases both paths pass.
        let both: Int
    }

    let rows: [Row]

    /// The parity read from `outputs`, keyed by case id; a case with no outputs counts against neither path.
    init(cases: [EvaluationCase], outputs: [String: Outputs]) {
        rows = FormattingClass.allCases.map { formattingClass in
            let tagged = cases.filter { $0.classes.contains(formattingClass) && outputs[$0.id] != nil }
            var onlyModel: [String] = []
            var onlyRules: [String] = []
            var refused: [String] = []
            var both = 0
            for testCase in tagged {
                guard let output = outputs[testCase.id] else { continue }
                let rules = Scorer.score(output.rules, against: testCase).passed
                let model = Scorer.score(output.delivered, against: testCase).passed
                if output.model == nil { refused.append(testCase.id) }
                switch (rules, model) {
                case (true, true): both += 1
                case (false, true): onlyModel.append(testCase.id)
                case (true, false): onlyRules.append(testCase.id)
                case (false, false): break
                }
            }
            return Row(
                formattingClass: formattingClass, caseIDs: tagged.map(\.id), onlyModel: onlyModel,
                onlyRules: onlyRules, refused: refused, both: both)
        }
    }

    /// The parity as the Markdown page `Docs/formatting-parity.md` holds.
    var markdown: String {
        var lines = [
            "# Formatting parity: rules path against model path",
            "",
            "Generated by `FormattingParityTests`; do not edit by hand.",
            "Regenerate with `UTTRFLOW_UPDATE_GOLDEN=1 swift test --filter FormattingParityTests`.",
            "Each tagged case runs through the rules alone and through the shipped model path, whose model",
            "answers with the case's expected text, so a gap is the rules' or the finishing passes', never the model's.",
            "A refused answer falls back to the rules' text, as the router does.",
            "",
            "| Class | Owner | Cases | Both pass | Only model path | Only rules | Refused |",
            "|---|---|---|---|---|---|---|",
        ]
        for row in rows {
            lines.append(
                "| \(row.formattingClass.rawValue) | \(row.formattingClass.ownership.owner.rawValue) "
                    + "| \(row.caseIDs.count) | \(row.both) | \(Self.ids(row.onlyModel)) "
                    + "| \(Self.ids(row.onlyRules)) | \(row.refused.count) |")
        }
        lines += [
            "",
            "## Model-only classes",
            "",
            "No pass writes these; the speech formats differently without the model by design.",
            "",
        ]
        for formattingClass in FormattingClass.allCases where formattingClass.ownership.owner == .model {
            lines.append("- `\(formattingClass.rawValue)`: \(formattingClass.ownership.reason)")
        }
        return lines.joined(separator: "\n") + "\n"
    }

    private static func ids(_ ids: [String]) -> String {
        ids.isEmpty ? "0" : "\(ids.count): " + ids.map { "`\($0)`" }.joined(separator: ", ")
    }
}
