// Homophone classes from common English words beyond the hand-kept ones, with invented carriers; written for this repository, copied from no list.

/// Classes of common words that sound the same or differ by one sound, kept for evaluation only; the repair path never reads them.
enum HomophoneLexiconClasses {
    /// Every class; none shares a spelling with `Homophones.groups`.
    static let all: [[String]] = [
        ["accept", "except"], ["affect", "effect"], ["then", "than"], ["lose", "loose"],
        ["advice", "advise"], ["quite", "quiet"], ["were", "we're"], ["desert", "dessert"],
        ["ad", "add"], ["aisle", "isle"], ["bare", "bear"], ["be", "bee"], ["beat", "beet"],
        ["blew", "blue"], ["cereal", "serial"], ["coarse", "course"], ["dear", "deer"],
        ["dew", "due"], ["feat", "feet"], ["flea", "flee"], ["grate", "great"], ["groan", "grown"],
        ["guessed", "guest"], ["hair", "hare"], ["hall", "haul"], ["heal", "heel"], ["hi", "high"],
        ["him", "hymn"], ["idle", "idol"], ["in", "inn"], ["jeans", "genes"], ["lead", "led"],
        ["loan", "lone"], ["minor", "miner"], ["missed", "mist"], ["nose", "knows"], ["not", "knot"],
        ["passed", "past"], ["patience", "patients"], ["pause", "paws"], ["poll", "pole"],
        ["pray", "prey"], ["presence", "presents"], ["rap", "wrap"], ["read", "red"],
        ["real", "reel"], ["ring", "wring"], ["sole", "soul"], ["some", "sum"], ["stair", "stare"],
        ["suite", "sweet"], ["tea", "tee"], ["tide", "tied"], ["waist", "waste"],
        ["which", "witch"], ["band", "banned"],
    ]
}

extension HomophoneCarriers {
    /// Two carriers for each spelling of `HomophoneLexiconClasses.all`.
    static let lexicon: [HomophoneCarrier] = [
        .init("accept", .role, "i _ your offer"), .init("accept", .sense, "do you _ cards here"),
        .init("except", .role, "everyone came _ sam"), .init("except", .role, "open daily _ sunday"),
        .init("affect", .role, "the rain will _ the match"), .init("affect", .role, "noise can _ your sleep"),
        .init("effect", .role, "the new rule took _ today"), .init("effect", .role, "the side _ was mild"),
        .init("then", .role, "eat first and _ rest"), .init("then", .role, "back _ we lived by the sea"),
        .init("than", .role, "she is taller _ me"), .init("than", .role, "more _ ten people came"),
        .init("lose", .role, "do not _ the ticket"), .init("lose", .sense, "we might _ the game"),
        .init("loose", .role, "the screw is _"), .init("loose", .sense, "wear _ clothes for yoga"),
        .init("advice", .role, "thanks for the good _"), .init("advice", .role, "can i ask your _"),
        .init("advise", .role, "i _ you to wait"), .init("advise", .role, "we _ all guests to book early"),
        .init("quite", .role, "it is _ cold outside"), .init("quite", .role, "i am not _ ready"),
        .init("quiet", .sense, "please keep _ in the library"),
        .init("quiet", .role, "the street is very _ at night"),
        .init("were", .role, "they _ late yesterday"), .init("were", .role, "we _ at home all day"),
        .init("we're", .role, "_ going to the park"), .init("we're", .role, "i think _ almost done"),
        .init("desert", .sense, "camels cross the hot _"),
        .init("desert", .sense, "the _ gets cold at night"),
        .init("dessert", .sense, "we had cake for _"),
        .init("dessert", .sense, "save room for _ after dinner"),
        .init("ad", .sense, "the _ ran on the radio"), .init("ad", .domain, "the _ campaign starts monday"),
        .init("add", .role, "please _ salt to taste"), .init("add", .domain, "_ a new row to the table"),
        .init("aisle", .sense, "the milk is in the third _"),
        .init("aisle", .sense, "she walked down the _ at the wedding"),
        .init("isle", .sense, "they sailed to a small _"), .init("isle", .none, "we saw the _ from far away"),
        .init("bare", .sense, "he walked on _ feet"), .init("bare", .role, "the walls are _"),
        .init("bear", .sense, "a brown _ crossed the road"), .init("bear", .role, "i cannot _ the noise"),
        .init("be", .role, "i will _ there soon"), .init("be", .role, "try to _ kind"),
        .init("bee", .sense, "a _ landed on the flower"), .init("bee", .sense, "the _ stung my arm"),
        .init("beat", .sense, "the drum kept a steady _"), .init("beat", .role, "we _ them last week"),
        .init("beet", .sense, "add a roasted _ to the salad"),
        .init("beet", .sense, "the _ juice stained the board"),
        .init("blew", .role, "the wind _ all night"), .init("blew", .role, "she _ out the candles"),
        .init("blue", .sense, "the sky is _ today"), .init("blue", .role, "i like the _ shirt"),
        .init("cereal", .sense, "i eat _ with milk"), .init("cereal", .sense, "a box of _ for breakfast"),
        .init("serial", .domain, "enter the _ number on the back"),
        .init("serial", .domain, "open the _ port"),
        .init("coarse", .sense, "use _ salt on the steak"), .init("coarse", .sense, "the sand feels _"),
        .init("course", .sense, "she took a cooking _"), .init("course", .role, "of _ you can come"),
        .init("dear", .role, "_ sam thanks for the gift"), .init("dear", .sense, "she is a _ friend"),
        .init("deer", .sense, "a _ ran into the forest"), .init("deer", .sense, "we saw a _ eating grass"),
        .init("dew", .sense, "the grass is wet with _"), .init("dew", .sense, "morning _ covered the car"),
        .init("due", .role, "the rent is _ on friday"), .init("due", .role, "the train is _ at six"),
        .init("feat", .sense, "climbing it was quite a _"), .init("feat", .sense, "an amazing _ of skill"),
        .init("feet", .sense, "my _ hurt after the walk"), .init("feet", .sense, "the wall is six _ high"),
        .init("flea", .sense, "the dog has a _"), .init("flea", .sense, "we bought lamps at the _ market"),
        .init("flee", .role, "they had to _ the fire"), .init("flee", .role, "the thief tried to _"),
        .init("grate", .role, "_ the cheese over the pasta"),
        .init("grate", .sense, "the fire burned in the _"),
        .init("great", .role, "that was a _ movie"), .init("great", .role, "you did a _ job"),
        .init("groan", .role, "i heard a loud _"), .init("groan", .sense, "the old door let out a _"),
        .init("grown", .role, "the kids have _ so much"),
        .init("grown", .sense, "these tomatoes are _ locally"),
        .init("guessed", .role, "i _ the answer right"), .init("guessed", .role, "nobody _ her age"),
        .init("guest", .role, "we have a _ tonight"), .init("guest", .domain, "join the wifi as a _"),
        .init("hair", .sense, "she cut her _ short"), .init("hair", .sense, "brush your _ before school"),
        .init("hare", .sense, "the _ raced the tortoise"), .init("hare", .none, "we saw a _"),
        .init("hall", .sense, "wait in the _ outside"), .init("hall", .sense, "the concert _ was full"),
        .init("haul", .role, "help me _ the boxes upstairs"), .init("haul", .sense, "it was a long _ home"),
        .init("heal", .role, "the cut will _ soon"), .init("heal", .role, "time helps to _ the pain"),
        .init("heel", .sense, "my _ hurts in these shoes"),
        .init("heel", .sense, "she broke a _ on the stairs"),
        .init("hi", .role, "_ how are you"), .init("hi", .role, "say _ to your mum"),
        .init("high", .sense, "the shelf is too _"), .init("high", .role, "prices are _ this year"),
        .init("him", .role, "i called _ yesterday"), .init("him", .role, "give _ the keys"),
        .init("hymn", .sense, "the choir sang a _"), .init("hymn", .sense, "we sang the last _ at church"),
        .init("idle", .role, "the machine sat _ all week"), .init("idle", .domain, "the process is _"),
        .init("idol", .sense, "the singer was her _"),
        .init("idol", .sense, "a golden _ stood in the temple"),
        .init("in", .role, "the keys are _ the drawer"), .init("in", .role, "i live _ town"),
        .init("inn", .sense, "we stayed at a small _"), .init("inn", .sense, "the _ serves dinner at seven"),
        .init("jeans", .sense, "i wore my old _"), .init("jeans", .sense, "these _ are too tight"),
        .init("genes", .sense, "eye colour is set by your _"),
        .init("genes", .sense, "the study mapped two _"),
        .init("lead", .sense, "old pipes were made of _"), .init("lead", .sense, "_ paint is not safe"),
        .init("led", .role, "she _ the team to a win"), .init("led", .role, "the path _ to a lake"),
        .init("loan", .sense, "the bank gave us a _"), .init("loan", .domain, "repay the _ by march"),
        .init("lone", .role, "a _ tree stood on the hill"), .init("lone", .role, "the _ rider came at dawn"),
        .init("minor", .role, "it is a _ problem"), .init("minor", .sense, "a _ cannot buy alcohol"),
        .init("miner", .sense, "the _ went down the shaft"), .init("miner", .sense, "a coal _ needs a lamp"),
        .init("missed", .role, "i _ the bus"), .init("missed", .role, "we _ you at the party"),
        .init("mist", .sense, "a thick _ covered the valley"), .init("mist", .sense, "the _ cleared by noon"),
        .init("nose", .sense, "my _ is runny"), .init("nose", .sense, "he broke his _ playing rugby"),
        .init("knows", .role, "she _ the way"), .init("knows", .role, "nobody _ the answer"),
        .init("not", .role, "i am _ hungry"), .init("not", .role, "do _ touch that"),
        .init("knot", .sense, "tie a _ in the rope"), .init("knot", .sense, "the _ in my shoelace is stuck"),
        .init("passed", .role, "she _ the exam"), .init("passed", .role, "we _ a shop on the way"),
        .init("past", .role, "it is ten _ five"), .init("past", .role, "forget the _"),
        .init("patience", .sense, "thanks for your _"),
        .init("patience", .sense, "teaching needs a lot of _"),
        .init("patients", .sense, "the doctor saw ten _ today"),
        .init("patients", .sense, "the ward has room for six _"),
        .init("pause", .role, "_ the video for a minute"), .init("pause", .domain, "press space to _"),
        .init("paws", .sense, "the cat licked its _"), .init("paws", .sense, "the dog has muddy _"),
        .init("poll", .sense, "the _ shows a close race"),
        .init("poll", .domain, "create a _ in the channel"),
        .init("pole", .sense, "the flag hung from a _"), .init("pole", .sense, "the north _ is cold"),
        .init("pray", .role, "they _ before meals"), .init("pray", .role, "we _ for rain"),
        .init("prey", .sense, "the hawk caught its _"), .init("prey", .sense, "mice are _ for owls"),
        .init("presence", .sense, "your _ is requested"),
        .init("presence", .domain, "the app shows each user's _"),
        .init("presents", .sense, "we opened the _ on christmas"),
        .init("presents", .sense, "wrap the _ tonight"),
        .init("rap", .sense, "he wrote a _ song"), .init("rap", .sense, "a sharp _ on the door"),
        .init("wrap", .role, "_ the gift in paper"), .init("wrap", .domain, "turn on word _ in the editor"),
        .init("read", .role, "i _ that book last year"), .init("read", .role, "have you _ the email"),
        .init("red", .sense, "stop at the _ light"), .init("red", .sense, "she wore a _ dress"),
        .init("real", .role, "is that a _ diamond"), .init("real", .sense, "the danger is _"),
        .init("reel", .sense, "wind the fishing _"), .init("reel", .domain, "post the clip as a _"),
        .init("ring", .sense, "the phone began to _"), .init("ring", .sense, "she wears a gold _"),
        .init("wring", .role, "_ out the wet towel"), .init("wring", .role, "do not _ the sweater"),
        .init("sole", .role, "he was the _ survivor"), .init("sole", .sense, "the _ of my shoe is worn"),
        .init("soul", .sense, "music feeds the _"), .init("soul", .sense, "she sings _ and jazz"),
        .init("some", .role, "can i have _ water"), .init("some", .role, "_ people left early"),
        .init("sum", .sense, "add the numbers to get the _"),
        .init("sum", .domain, "use the _ formula in cell c"),
        .init("stair", .sense, "he sat on the top _"), .init("stair", .sense, "mind the loose _"),
        .init("stare", .role, "do not _ at people"), .init("stare", .role, "they _ at the screen all day"),
        .init("suite", .sense, "we booked a hotel _"), .init("suite", .domain, "the test _ passed"),
        .init("sweet", .sense, "the cake is too _"), .init("sweet", .role, "that is so _ of you"),
        .init("tea", .sense, "a cup of _ with milk"), .init("tea", .sense, "i drink green _"),
        .init("tee", .sense, "place the ball on the _"), .init("tee", .none, "she bought a new _"),
        .init("tide", .sense, "the _ is out"), .init("tide", .sense, "high _ comes at noon"),
        .init("tied", .role, "the game was _ at half time"), .init("tied", .role, "he _ his shoes"),
        .init("waist", .sense, "the belt fits my _"), .init("waist", .sense, "the water came up to my _"),
        .init("waste", .role, "do not _ food"), .init("waste", .role, "that was a _ of time"),
        .init("which", .role, "_ one do you want"), .init("which", .role, "tell me _ bus to take"),
        .init("witch", .sense, "the _ rode a broom"),
        .init("witch", .sense, "she dressed as a _ for the party"),
        .init("band", .sense, "the _ played all night"), .init("band", .sense, "tie it with a rubber _"),
        .init("banned", .role, "phones are _ in class"), .init("banned", .role, "he was _ from the club"),
    ]
}
