// Invented carrier sentences for every spelling of the hand-kept homophone classes; written for this repository, copied from no list.

/// Two carriers for each spelling, so every member of a class is both a meant word and a misreading.
public enum HomophoneCarriers {
    /// Every carrier.
    public static let all: [HomophoneCarrier] = [
        .init("allowed", .role, "dogs are not _ in the shop"),
        .init("allowed", .sense, "we were _ an extra hour"),
        .init("aloud", .sense, "please read the letter _"),
        .init("aloud", .role, "she laughed _ at the joke"),
        .init("bored", .role, "the kids got _ on the long drive"),
        .init("bored", .sense, "i was _ by the slides"),
        .init("board", .role, "pin the note to the _"), .init("board", .sense, "the _ meets on monday"),
        .init("brake", .sense, "press the _ before the turn"), .init("brake", .role, "the front _ squeaks"),
        .init("break", .sense, "take a short _ after lunch"), .init("break", .role, "do not _ the glass"),
        .init("capital", .sense, "the _ city is in the north"),
        .init("capital", .domain, "raise more _ for the fund"),
        .init("capitol", .sense, "the senators met inside the _ building"),
        .init("capitol", .none, "we walked past the _"),
        .init("by", .role, "the report is due _ friday"),
        .init("by", .role, "the book was written _ my aunt"),
        .init("buy", .role, "i want to _ new shoes"), .init("buy", .sense, "we can _ milk on the way"),
        .init("bye", .sense, "say _ to your grandmother"), .init("bye", .role, "she waved _ from the car"),
        .init("cache", .domain, "clear the _ and rebuild"), .init("cache", .domain, "the browser _ is full"),
        .init("cash", .sense, "pay in _ at the counter"), .init("cash", .sense, "i have no _ on me"),
        .init("cell", .sense, "the prisoner sat in his _"),
        .init("cell", .domain, "select the _ in column b"),
        .init("sell", .role, "they want to _ the house"),
        .init("sell", .sense, "we _ fresh bread every morning"),
        .init("sent", .role, "i _ the file this morning"), .init("sent", .role, "the parcel was _ yesterday"),
        .init("cent", .sense, "it costs one _ more"), .init("cent", .sense, "every _ of the budget is spent"),
        .init("scent", .sense, "the dog followed the _"), .init("scent", .sense, "the soap has a fresh _"),
        .init("site", .sense, "the building _ is closed"), .init("site", .domain, "deploy the _ to staging"),
        .init("sight", .sense, "the castle was a lovely _"), .init("sight", .role, "my _ is getting worse"),
        .init("cite", .role, "please _ your sources"),
        .init("cite", .sense, "you must _ the paper you quote"),
        .init("complement", .sense, "the sauce is a good _ to the fish"),
        .init("complement", .role, "the colours _ each other"),
        .init("compliment", .sense, "thanks for the kind _"),
        .init("compliment", .role, "she likes to _ her team"),
        .init("die", .role, "the plants will _ without water"), .init("die", .sense, "roll the _ twice"),
        .init("dye", .sense, "she used blue _ on the shirt"), .init("dye", .role, "we will _ the fabric red"),
        .init("fair", .sense, "that is not _ to the others"), .init("fair", .role, "we went to the county _"),
        .init("fare", .sense, "the bus _ went up"), .init("fare", .sense, "pay the _ to the driver"),
        .init("ate", .role, "we _ dinner late"), .init("ate", .role, "the dog _ my sandwich"),
        .init("eight", .role, "the meeting starts at _"), .init("eight", .role, "we need _ chairs"),
        .init("flew", .role, "the bird _ away"), .init("flew", .role, "we _ home on sunday"),
        .init("flu", .sense, "she stayed in bed with the _"),
        .init("flu", .sense, "get your _ shot this week"),
        .init("flour", .sense, "add a cup of _ to the bowl"),
        .init("flour", .sense, "the bread needs more _"),
        .init("flower", .sense, "she picked a red _"), .init("flower", .sense, "water the _ on the window"),
        .init("for", .role, "this gift is _ you"), .init("for", .role, "wait _ me at the gate"),
        .init("four", .role, "we have _ cats"), .init("four", .role, "the train leaves at _"),
        .init("hear", .role, "i can _ the rain"), .init("hear", .role, "did you _ the news"),
        .init("here", .role, "put the box down _"), .init("here", .role, "come over _ please"),
        .init("hole", .sense, "there is a _ in my sock"), .init("hole", .sense, "the dog dug a _"),
        .init("whole", .role, "i ate the _ pie"), .init("whole", .role, "the _ team came"),
        .init("hour", .role, "wait an _ please"), .init("hour", .sense, "the drive takes one _"),
        .init("our", .role, "this is _ house"), .init("our", .role, "_ train is late"),
        .init("its", .role, "the dog wagged _ tail"), .init("its", .role, "the app lost _ settings"),
        .init("it's", .role, "_ raining again"), .init("it's", .role, "i think _ ready"),
        .init("lets", .role, "she _ the cat out at night"),
        .init("lets", .role, "the tool _ you undo a change"),
        .init("let's", .role, "_ go to the park"), .init("let's", .role, "_ meet after lunch"),
        .init("knew", .role, "i _ the answer"), .init("knew", .role, "she _ him from school"),
        .init("new", .role, "i bought a _ phone"), .init("new", .role, "open a _ tab"),
        .init("knight", .sense, "the _ rode a white horse"),
        .init("knight", .sense, "move the _ to the left"),
        .init("night", .sense, "we stayed up all _"), .init("night", .role, "the _ was cold"),
        .init("know", .role, "i _ the way"), .init("know", .role, "do you _ her name"),
        .init("no", .role, "there is _ milk left"), .init("no", .none, "she said _ to the offer"),
        .init("mail", .sense, "the _ came early today"), .init("mail", .role, "please _ the forms to me"),
        .init("male", .sense, "the _ bird has red feathers"),
        .init("male", .none, "the patient is a _ aged forty"),
        .init("made", .role, "she _ a cake"), .init("made", .role, "the chair is _ of oak"),
        .init("maid", .sense, "the _ cleaned the room"), .init("maid", .sense, "she was _ of honour"),
        .init("meat", .sense, "the _ is in the oven"), .init("meat", .sense, "he does not eat _"),
        .init("meet", .role, "let us _ at noon"), .init("meet", .role, "nice to _ you"),
        .init("need", .role, "i _ more time"), .init("need", .role, "we _ to leave now"),
        .init("knead", .sense, "_ the dough for ten minutes"),
        .init("knead", .sense, "flour your hands and _ the bread"),
        .init("one", .role, "i have _ brother"), .init("one", .role, "pick _ of the two"),
        .init("won", .role, "we _ the match on sunday"), .init("won", .role, "she _ first prize"),
        .init("pain", .sense, "my back is in _"), .init("pain", .sense, "take something for the _"),
        .init("pane", .sense, "the window _ is cracked"),
        .init("pane", .domain, "split the editor into a second _"),
        .init("pair", .sense, "she bought a _ of socks"),
        .init("pair", .domain, "_ the keyboard with the laptop"),
        .init("pear", .sense, "i ate a ripe _"), .init("pear", .sense, "the _ tree is in bloom"),
        .init("peace", .sense, "the treaty brought _"), .init("peace", .sense, "i want some _ and quiet"),
        .init("piece", .sense, "take a _ of the cake"), .init("piece", .sense, "the last _ of the puzzle"),
        .init("peak", .sense, "we climbed to the _"), .init("peak", .sense, "traffic is at its _ now"),
        .init("peek", .sense, "take a _ at the draft"), .init("peek", .role, "do not _ at the answers"),
        .init("plain", .sense, "i like _ yoghurt"), .init("plain", .domain, "save it as _ text"),
        .init("plane", .sense, "the _ landed late"), .init("plane", .sense, "we boarded the _ at noon"),
        .init("principal", .sense, "the _ called my parents"),
        .init("principal", .domain, "pay off the _ first"),
        .init("principle", .sense, "it is a matter of _"),
        .init("principle", .sense, "the first _ of design"),
        .init("rain", .sense, "the _ stopped at noon"), .init("rain", .role, "it will _ tomorrow"),
        .init("reign", .sense, "the queen's _ lasted years"),
        .init("reign", .sense, "during the _ of the old king"),
        .init("rein", .sense, "hold the _ tight on the horse"), .init("rein", .sense, "pull the left _"),
        .init("road", .sense, "the _ is closed"), .init("road", .sense, "cross the _ carefully"),
        .init("rode", .role, "she _ the bus home"), .init("rode", .role, "we _ our bikes to the lake"),
        .init("root", .domain, "log in as _ on the test box"),
        .init("root", .sense, "the tree _ broke the pipe"),
        .init("route", .sense, "take the scenic _"), .init("route", .domain, "add a _ for the login page"),
        .init("role", .sense, "she got the lead _"), .init("role", .domain, "give the user the admin _"),
        .init("roll", .sense, "pass me a bread _"), .init("roll", .role, "_ the dice"),
        .init("sail", .role, "we _ at dawn"), .init("sail", .sense, "the _ tore in the storm"),
        .init("sale", .sense, "the shoes are on _ today"), .init("sale", .sense, "the house is for _"),
        .init("scene", .sense, "the last _ of the film"), .init("scene", .sense, "police arrived at the _"),
        .init("seen", .role, "have you _ my keys"), .init("seen", .role, "i have _ that film"),
        .init("sea", .sense, "we swam in the _"), .init("sea", .sense, "the _ was rough"),
        .init("see", .role, "i can _ the hills"), .init("see", .role, "come and _ me"),
        .init("son", .sense, "our _ starts school today"), .init("son", .sense, "she has a _ and a daughter"),
        .init("sun", .sense, "the _ is setting"), .init("sun", .sense, "sit in the _ for a while"),
        .init("stationary", .sense, "the car was _ at the lights"),
        .init("stationary", .sense, "keep the camera _"),
        .init("stationery", .sense, "order more _ for the office"),
        .init("stationery", .sense, "the _ shop sells pens"),
        .init("steal", .role, "do not _ my idea"), .init("steal", .role, "they tried to _ the bike"),
        .init("steel", .sense, "the beam is made of _"), .init("steel", .sense, "a _ door"),
        .init("tail", .sense, "the dog wagged its _"), .init("tail", .domain, "_ the log file"),
        .init("tale", .sense, "she told a bedtime _"), .init("tale", .sense, "an old fairy _"),
        .init("there", .role, "put it over _"), .init("there", .role, "_ is a problem"),
        .init("their", .role, "_ car is parked outside"), .init("their", .role, "the kids lost _ coats"),
        .init("they're", .role, "_ coming at six"), .init("they're", .role, "i think _ right"),
        .init("threw", .role, "he _ the ball"), .init("threw", .role, "she _ out the old chairs"),
        .init("through", .role, "walk _ the door"), .init("through", .role, "read it _ once more"),
        .init("to", .role, "we went _ the shop"), .init("to", .role, "i want _ sleep"),
        .init("too", .role, "it is _ hot"), .init("too", .role, "i want one _"),
        .init("two", .role, "we have _ dogs"), .init("two", .role, "meet me at _"),
        .init("toe", .sense, "i stubbed my _"), .init("toe", .sense, "the shoe hurts my big _"),
        .init("tow", .sense, "they had to _ the car"), .init("tow", .sense, "call a _ truck"),
        .init("vain", .sense, "we tried in _"), .init("vain", .sense, "he is too _ to listen"),
        .init("vein", .sense, "the nurse found a _"), .init("vein", .sense, "a _ of gold in the rock"),
        .init("wait", .role, "please _ here"), .init("wait", .role, "i cannot _ any longer"),
        .init("weight", .sense, "check the _ of the parcel"), .init("weight", .sense, "she lost some _"),
        .init("way", .sense, "this is the _ home"), .init("way", .role, "there is no _ out"),
        .init("weigh", .role, "_ the flour first"), .init("weigh", .role, "how much do you _"),
        .init("wear", .role, "i will _ the blue coat"), .init("wear", .role, "what should i _"),
        .init("where", .role, "_ are my keys"), .init("where", .role, "tell me _ you live"),
        .init("weather", .sense, "the _ is cold today"), .init("weather", .sense, "check the _ before we go"),
        .init("whether", .role, "ask _ it is open"), .init("whether", .role, "i do not know _ to stay"),
        .init("weak", .sense, "the signal is _ here"), .init("weak", .role, "my legs feel _"),
        .init("week", .sense, "we ship next _"), .init("week", .sense, "i run three times a _"),
        .init("wood", .sense, "the table is made of _"), .init("wood", .sense, "we walked in the _"),
        .init("would", .role, "i _ like some tea"), .init("would", .role, "_ you help me"),
        .init("right", .sense, "turn _ at the corner"), .init("right", .sense, "you are _ about that"),
        .init("write", .role, "please _ your name here"), .init("write", .role, "i will _ to you"),
        .init("rite", .sense, "the wedding _ was short"), .init("rite", .sense, "an old _ of passage"),
        .init("your", .role, "is this _ bag"), .init("your", .role, "wash _ hands"),
        .init("you're", .role, "_ late again"), .init("you're", .role, "i hope _ well"),
    ]
}
