public import UttrflowCore

/// The last resort: leaves the text on the clipboard and says so, so the words are never lost.
public struct ClipboardTextInsertionEngine: TextInsertionEngine {
    /// Not `.pasteboard`: this says the words are waiting, where that says a paste landed.
    public let method: TextInsertionMethod = .clipboard

    private let pasteboard: any Pasteboard
    /// Asked whether the field the words were meant for is secure, so what is left behind is concealed.
    private let focus: (any AccessibilityFocus)?
    private let secretClassifier: @Sendable (String) -> Bool

    public init(
        pasteboard: any Pasteboard,
        focus: (any AccessibilityFocus)? = nil,
        secretClassifier: @escaping @Sendable (String) -> Bool = { _ in false }
    ) {
        self.pasteboard = pasteboard
        self.focus = focus
        self.secretClassifier = secretClassifier
    }

    /// Always. A clipboard is always available, which is the point of having this.
    public func canInsert() async -> Bool { true }

    /// Answers `.notReported`: nothing was sent anywhere, so there is no arrival to have an opinion about.
    public func insert(_ text: String) async throws(TextInsertionError) -> InsertionArrival {
        // Even the floor: the words are already kept in History, and the clipboard is the user's.
        try PasteboardInsertionCancellation.requireLive(on: pasteboard)
        let focus = focus
        let isSecret = secretClassifier(text)
        let shouldConceal: Bool
        if isSecret {
            shouldConceal = true
        } else {
            shouldConceal = await AccessibilityThread.run(
                orElse: true, { focus?.focusedFieldIsSecure() == true })
        }
        try PasteboardInsertionCancellation.requireLive(on: pasteboard)
        let write: PasteboardWriteResult
        if shouldConceal {
            write = pasteboard.writeConcealedText(text)
        } else {
            write = pasteboard.writeAutoGeneratedText(text)
        }
        try PasteboardInsertionCancellation.requireLive(
            on: pasteboard, afterWritingAt: write.changeCount)
        guard write.didWrite else { throw .clipboardUnavailable }
        let writeChangeCount = write.changeCount
        let readback = pasteboard.text()
        let readbackChangeCount = pasteboard.changeCount()
        if let writeChangeCount, let readbackChangeCount,
            writeChangeCount != readbackChangeCount
        {
            throw .clipboardChanged
        }
        guard readback == text else { throw .clipboardUnavailable }
        try PasteboardInsertionCancellation.requireLive(
            on: pasteboard, afterWritingAt: writeChangeCount)
        return .notReported
    }
}
