public import struct Foundation.Data

/// A pasteboard that marks every text write concealed, for words the app already knows are a secret.
public struct ConcealingPasteboard: Pasteboard {
    private let base: any Pasteboard

    /// Wraps the pasteboard the writes go through, so its announcements still happen.
    public init(_ base: any Pasteboard) {
        self.base = base
    }

    public func text() -> String? { base.text() }

    public func changeCount() -> Int? { base.changeCount() }

    public func discardContents(ifUnchangedSince changeCount: Int) -> Bool {
        base.discardContents(ifUnchangedSince: changeCount)
    }

    public func setText(_ text: String) -> PasteboardWriteResult { base.setConcealedText(text) }

    /// The formatted flavour is dropped, since a concealed write carries the plain words alone.
    public func setText(_ text: String, richText: String?) -> PasteboardWriteResult {
        base.setConcealedText(text)
    }

    public func setConcealedText(_ text: String) -> PasteboardWriteResult { base.setConcealedText(text) }

    public func writeText(_ text: String, richText: String?) -> PasteboardWriteResult {
        base.writeConcealedText(text)
    }

    public func writeTransientText(_ text: String, richText: String?) -> PasteboardWriteResult {
        base.writeConcealedText(text)
    }

    public func writeAutoGeneratedText(_ text: String) -> PasteboardWriteResult {
        base.writeConcealedText(text)
    }

    public func writeConcealedText(_ text: String) -> PasteboardWriteResult {
        base.writeConcealedText(text)
    }

    public func setImage(_ data: Data) -> PasteboardWriteResult { base.setImage(data) }
}
