public import UttrflowCore
public import struct Foundation.Data

/// Whether the pasteboard accepted a write, and the generation it created when observable.
public enum PasteboardWriteResult: Sendable, Equatable {
    case written(changeCount: Int?)
    case refused

    /// Whether the pasteboard accepted the contents.
    public var didWrite: Bool {
        if case .written = self { true } else { false }
    }

    /// The generation created by the write, when the pasteboard exposes one.
    public var changeCount: Int? {
        guard case .written(let changeCount) = self else { return nil }
        return changeCount
    }
}

/// The system clipboard, reduced to what insertion needs and testable without touching the real one.
public protocol Pasteboard: Sendable {
    /// The current text, or `nil` when the clipboard holds something else.
    func text() -> String?
    /// A token that changes whenever the clipboard is written, or `nil` when ownership cannot be observed.
    func changeCount() -> Int?
    /// Discards the current contents only when this generation still belongs to the caller.
    func discardContents(ifUnchangedSince changeCount: Int) -> Bool
    /// Replaces the contents.
    func setText(_ text: String) -> PasteboardWriteResult

    /// The same write, with the formatted flavour alongside where there is one.
    func setText(_ text: String, richText: String?) -> PasteboardWriteResult

    /// Replaces the contents with words marked concealed, so clipboard histories keep them out.
    func setConcealedText(_ text: String) -> PasteboardWriteResult

    /// Writes text and returns the generation created by that write.
    func writeText(_ text: String, richText: String?) -> PasteboardWriteResult

    /// Writes dictated text as a paste that clipboard histories should not retain.
    func writeTransientText(_ text: String, richText: String?) -> PasteboardWriteResult

    /// Writes dictated text as generated content that clipboard histories should not retain.
    func writeAutoGeneratedText(_ text: String) -> PasteboardWriteResult

    /// Writes concealed text and returns the generation created by that write.
    func writeConcealedText(_ text: String) -> PasteboardWriteResult

    /// K4 — replaces the contents with a picture, as PNG bytes, so no caller needs the platform clipboard.
    func setImage(_ data: Data) -> PasteboardWriteResult
}

/// Sends the keystroke that pastes.
public protocol KeystrokeSender: Sendable {
    /// Presses ⌘V, refusing with ``TextInsertionError/accessibilityDenied`` where macOS forbids it.
    func sendPaste() throws(TextInsertionError)
    /// Whether macOS lets this app post the paste key, asked before the clipboard is taken for it.
    func maySendPaste() -> Bool
}

extension KeystrokeSender {
    /// A sender that cannot tell beforehand answers at the key itself.
    public func maySendPaste() -> Bool { true }
}

extension Pasteboard {
    /// Test doubles and pasteboards without ownership tracking may decline this check.
    public func changeCount() -> Int? { nil }

    /// Pasteboards without generation-aware clearing leave their contents untouched.
    public func discardContents(ifUnchangedSince changeCount: Int) -> Bool { false }

    /// A pasteboard that cannot carry formatting simply writes the words.
    public func setText(_ text: String, richText: String?) -> PasteboardWriteResult { setText(text) }

    /// Captures the generation immediately after the write.
    public func writeText(_ text: String, richText: String?) -> PasteboardWriteResult {
        let result = setText(text, richText: richText)
        guard result.didWrite else { return .refused }
        return .written(changeCount: result.changeCount ?? changeCount())
    }

    /// Pasteboards without marker support write the same text flavours.
    public func writeTransientText(_ text: String, richText: String?) -> PasteboardWriteResult {
        writeText(text, richText: richText)
    }

    /// Pasteboards without marker support write the same text flavour.
    public func writeAutoGeneratedText(_ text: String) -> PasteboardWriteResult {
        writeText(text, richText: nil)
    }

    /// Captures the generation immediately after the concealed write.
    public func writeConcealedText(_ text: String) -> PasteboardWriteResult {
        let result = setConcealedText(text)
        guard result.didWrite else { return .refused }
        return .written(changeCount: result.changeCount ?? changeCount())
    }
}

enum PasteboardInsertionCancellation {
    static func requireLive(
        on pasteboard: any Pasteboard, afterWritingAt changeCount: Int? = nil
    ) throws(TextInsertionError) {
        guard Task.isCancelled else { return }
        if let changeCount { _ = pasteboard.discardContents(ifUnchangedSince: changeCount) }
        throw .insertionCancelled
    }
}
