import AppKit
import ApplicationServices
public import Foundation
public import UttrflowCore
private import UttrflowContext
public import UttrflowPredict

private import Carbon
private import Synchronization

/// Calls the Accessibility framework's exported window-number SPI.
@_silgen_name("_AXUIElementGetWindow")
private func axUIElementGetWindow(
    _ element: AXUIElement, _ window: UnsafeMutablePointer<CGWindowID>
) -> AXError

/// The real clipboard, untestable by construction and so excluded from the coverage gate.
public struct SystemPasteboard: Pasteboard {
    /// Told what this app is about to write, so the watcher can tell it from a copy. See `Docs/insertion.md`.
    private let willWrite: @Sendable (String) -> @Sendable (Int?) -> Void
    /// Told the bytes a picture write puts there, which is what names it to the watcher.
    private let willWritePicture: @Sendable (Data) -> @Sendable (Int?) -> Void

    /// Takes the announcements the clipboard watcher needs, and by default makes none.
    public init(
        willWrite: @escaping @Sendable (String) -> @Sendable (Int?) -> Void = { _ in { _ in } },
        willWritePicture: @escaping @Sendable (Data) -> @Sendable (Int?) -> Void = { _ in { _ in } }
    ) {
        self.willWrite = willWrite
        self.willWritePicture = willWritePicture
    }

    public func text() -> String? {
        NSPasteboard.general.string(forType: .string)
    }

    public func changeCount() -> Int? {
        NSPasteboard.general.changeCount
    }

    public func discardContents(ifUnchangedSince changeCount: Int) -> Bool {
        guard NSPasteboard.general.changeCount == changeCount else { return false }
        clearForThisMacOnly()
        return true
    }

    /// E2 — the plain flavour always, the formatted one beside it when the clip has one.
    public func setText(_ text: String, richText: String?) -> PasteboardWriteResult {
        writeText(text, richText: richText)
    }

    public func writeText(_ text: String, richText: String?) -> PasteboardWriteResult {
        let finishAnnouncement = willWrite(text)
        let item = Self.textItem(text, richText: richText)
        clearForThisMacOnly()
        guard NSPasteboard.general.writeObjects([item]) else {
            finishAnnouncement(nil)
            return .refused
        }
        guard NSPasteboard.general.string(forType: .string) == text else {
            finishAnnouncement(nil)
            return .refused
        }
        let changeCount = NSPasteboard.general.changeCount
        finishAnnouncement(changeCount)
        return .written(changeCount: changeCount)
    }

    public func writeTransientText(_ text: String, richText: String?) -> PasteboardWriteResult {
        writeMarkedText(text, richText: richText, marker: .transient)
    }

    public func writeAutoGeneratedText(_ text: String) -> PasteboardWriteResult {
        writeMarkedText(text, richText: nil, marker: .autoGenerated)
    }

    public func setText(_ text: String) -> PasteboardWriteResult {
        writeText(text, richText: nil)
    }

    /// The plain flavour beside the concealed marker, which clipboard managers read as a password.
    public func setConcealedText(_ text: String) -> PasteboardWriteResult {
        writeConcealedText(text)
    }

    public func writeConcealedText(_ text: String) -> PasteboardWriteResult {
        let finishAnnouncement = willWrite(text)
        // Built whole and written once, so no reader sees the words before the marker.
        let item = Self.textItem(text, richText: nil, marker: .concealed)
        clearForThisMacOnly()
        guard NSPasteboard.general.writeObjects([item]) else {
            finishAnnouncement(nil)
            return .refused
        }
        guard NSPasteboard.general.string(forType: .string) == text else {
            finishAnnouncement(nil)
            return .refused
        }
        let changeCount = NSPasteboard.general.changeCount
        finishAnnouncement(changeCount)
        return .written(changeCount: changeCount)
    }

    private func writeMarkedText(
        _ text: String, richText: String?, marker: PasteboardMarkers
    ) -> PasteboardWriteResult {
        let finishAnnouncement = willWrite(text)
        let item = Self.textItem(text, richText: richText, marker: marker)
        clearForThisMacOnly()
        guard NSPasteboard.general.writeObjects([item]) else {
            finishAnnouncement(nil)
            return .refused
        }
        guard NSPasteboard.general.string(forType: .string) == text else {
            finishAnnouncement(nil)
            return .refused
        }
        let changeCount = NSPasteboard.general.changeCount
        finishAnnouncement(changeCount)
        return .written(changeCount: changeCount)
    }

    static func textItem(
        _ text: String, richText: String?, marker: PasteboardMarkers = []
    ) -> NSPasteboardItem {
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        if let richText { item.setString(richText, forType: .html) }
        for type in marker.typeIdentifiers {
            item.setData(Data(), forType: NSPasteboard.PasteboardType(type))
        }
        return item
    }

    /// K4 — the picture flavour, announced by its bytes and kept off Universal Clipboard like every other write.
    public func setImage(_ data: Data) -> PasteboardWriteResult {
        let finishAnnouncement = willWritePicture(data)
        clearForThisMacOnly()
        guard NSPasteboard.general.setData(data, forType: .png) else {
            finishAnnouncement(nil)
            return .refused
        }
        let changeCount = NSPasteboard.general.changeCount
        finishAnnouncement(changeCount)
        return .written(changeCount: changeCount)
    }

    /// Clears the pasteboard and keeps what goes on it next off Universal Clipboard. See `Docs/insertion.md`.
    private func clearForThisMacOnly() {
        NSPasteboard.general.prepareForNewContents(with: .currentHostOnly)
    }
}

/// What every failure to build a synthetic keystroke reports.
private let unmakeableKeystroke = "could not create the keystroke"

/// Posts one tagged key-down and key-up, after `prepare` has set each up. See `Docs/input-synthetic-keystrokes.md`.
private func postTaggedKeyPair(
    from source: CGEventSource, keyCode: CGKeyCode, prepare: (CGEvent) -> Void
) throws(TextInsertionError) {
    let pair = try makeTaggedKeyPair(from: source, keyCode: keyCode, prepare: prepare)
    postTaggedKeyPairs([pair])
}

private func makeTaggedKeyPair(
    from source: CGEventSource, keyCode: CGKeyCode, prepare: (CGEvent) -> Void
) throws(TextInsertionError) -> (down: CGEvent, up: CGEvent) {
    guard
        let keyDown = CGEvent(keyboardEventSource: source, virtualKey: keyCode, keyDown: true),
        let keyUp = CGEvent(keyboardEventSource: source, virtualKey: keyCode, keyDown: false)
    else { throw .insertionRejected(description: unmakeableKeystroke) }

    for event in [keyDown, keyUp] {
        prepare(event)
        SyntheticEvent.tag(event)
    }
    return (keyDown, keyUp)
}

func buildThenPost<Input, Output>(
    _ inputs: [Input], build: (Input) throws(TextInsertionError) -> Output,
    post: ([Output]) -> Void
) throws(TextInsertionError) {
    post(try inputs.map(build))
}

private func postTaggedKeyPairs(_ pairs: [(down: CGEvent, up: CGEvent)]) {
    for pair in pairs {
        // The one pair that reaches another application. See `Docs/insertion.md`.
        pair.down.post(tap: .cghidEventTap)
        pair.up.post(tap: .cghidEventTap)
    }
}

/// The key code posted when no keyboard layout can be read, `v`'s position on a US QWERTY board.
private let fallbackVKeyCode: CGKeyCode = 9

/// The key code for ⌘V, resolved from the layout the target interprets shortcuts with. See `Docs/input-synthetic-keystrokes.md`.
enum PasteKeyLayout {
    /// `v`, the character ⌘V is a shortcut for regardless of the key that types it.
    private static let vCharacter = UniChar(UnicodeScalar("v").value)

    /// The last resolved key code, readable from any thread without a Text Input Sources call.
    private static let cachedKeyCode = Mutex<CGKeyCode>(fallbackVKeyCode)
    private static let cachedLayout = Mutex<Data?>(nil)

    /// Whether the change notification is already being watched, so starting twice still observes once.
    @MainActor private static var observing = false

    /// The cached key code for ⌘V, filled by `startObserving()` and kept current after that.
    static func vKeyCode() -> CGKeyCode {
        cachedKeyCode.withLock { $0 }
    }

    /// Fills the cache and keeps it filled, which every off-main reader depends on having been called.
    @MainActor
    static func startObserving() {
        guard !observing else { return }
        observing = true
        DistributedNotificationCenter.default().addObserver(
            forName: Notification.Name(kTISNotifySelectedKeyboardInputSourceChanged as String),
            object: nil, queue: nil
        ) { _ in
            // Back to the main queue explicitly, because HIToolbox asserts it and the poster is not it.
            DispatchQueue.main.async { MainActor.assumeIsolated { _ = refresh() } }
        }
        refresh()
    }

    /// Asks Text Input Sources what is selected and caches its ⌘V key code, the one place that calls TIS.
    @MainActor
    @discardableResult
    static func refresh() -> CGKeyCode {
        let selected = TISCopyCurrentKeyboardInputSource()?.takeRetainedValue()
        let selectedData = selected.flatMap(unicodeLayoutData(of:))
        cachedLayout.withLock { $0 = selectedData }
        let code = readVKeyCode()
        cachedKeyCode.withLock { $0 = code }
        return code
    }

    /// The current layout's key code for ⌘V, read from its ⌘ table, or the ASCII-capable layout's when the current one has none.
    @MainActor
    private static func readVKeyCode() -> CGKeyCode {
        if let source = TISCopyCurrentKeyboardInputSource()?.takeRetainedValue(),
            let data = unicodeLayoutData(of: source),
            let code = LayoutKeyCode.code(for: vCharacter, in: data, modifiers: LayoutKeyCode.commandHeld)
        {
            return code
        }
        if let source = TISCopyCurrentASCIICapableKeyboardLayoutInputSource()?.takeRetainedValue(),
            let data = unicodeLayoutData(of: source),
            let code = LayoutKeyCode.code(for: vCharacter, in: data, modifiers: LayoutKeyCode.commandHeld)
        {
            return code
        }
        return fallbackVKeyCode
    }

    /// The key code `character` types with ⌘ held under the cached layout, or `fallback` when it has none.
    static func commandKeyCode(for character: UniChar, fallback: CGKeyCode) -> CGKeyCode {
        guard let data = cachedLayout.withLock({ $0 }),
            let code = LayoutKeyCode.code(for: character, in: data, modifiers: LayoutKeyCode.commandHeld)
        else { return fallback }
        return code
    }

    /// The selected layout table cached by `refresh()`, which lets posted text use matching physical keys.
    static func stroke(for character: UniChar) -> LayoutKeyCode.Stroke? {
        guard let data = cachedLayout.withLock({ $0 }) else { return nil }
        return LayoutKeyCode.stroke(for: character, in: data)
    }

    /// The raw layout table Text Input Sources holds for `source`, absent for input methods and the like.
    private static func unicodeLayoutData(of source: TISInputSource) -> Data? {
        guard let property = TISGetInputSourceProperty(source, kTISPropertyUnicodeKeyLayoutData)
        else { return nil }
        return Unmanaged<CFData>.fromOpaque(property).takeUnretainedValue() as Data
    }
}

/// Presses ⌘V by posting keyboard events, which no test can assert anything about.
public struct CGEventKeystrokeSender: KeystrokeSender {
    public init() {}

    /// Starts tracking layout changes, so `sendPaste()` posts the key that types V under the current one.
    @MainActor
    public static func startObservingLayout() {
        PasteKeyLayout.startObserving()
    }

    public func sendPaste() throws(TextInsertionError) {
        guard AXIsProcessTrusted() else { throw .accessibilityDenied }
        guard let source = CGEventSource(stateID: .hidSystemState) else {
            throw .insertionRejected(description: unmakeableKeystroke)
        }
        try postTaggedKeyPair(from: source, keyCode: PasteKeyLayout.vKeyCode()) { $0.flags = .maskCommand }
    }
}

extension CGEventKeystrokeSender {
    /// `z`'s position on a US QWERTY board, posted when no layout has been read.
    private static let fallbackZKeyCode: CGKeyCode = 6

    /// Presses ⌘Z once, which is how `uttrflow-dev insert --then-undo` asks the target to undo.
    public func sendUndo() throws(TextInsertionError) {
        guard AXIsProcessTrusted() else { throw .accessibilityDenied }
        guard let source = CGEventSource(stateID: .hidSystemState) else {
            throw .insertionRejected(description: unmakeableKeystroke)
        }
        let code = PasteKeyLayout.commandKeyCode(
            for: UniChar(UnicodeScalar("z").value), fallback: Self.fallbackZKeyCode)
        try postTaggedKeyPair(from: source, keyCode: code) { $0.flags = .maskCommand }
    }
}

/// Types each character on its layout key where the layout has one, and as a bare Unicode string where it does not.
public struct CGEventTypist: KeystrokeTyping {
    /// Virtual key code for Delete, positional and so correct on any keyboard layout.
    private static let deleteKeyCode: CGKeyCode = 51

    public init() {}

    /// One press per character, because there is no bulk delete a synthetic keyboard can reach for.
    public func deleteBackwards(_ count: Int) throws(TextInsertionError) {
        guard count > 0 else { return }
        guard AXIsProcessTrusted() else { throw .accessibilityDenied }
        guard let source = CGEventSource(stateID: .hidSystemState) else {
            throw .insertionRejected(description: unmakeableKeystroke)
        }
        try buildThenPost(
            Array(0..<count),
            build: { _ throws(TextInsertionError) in
                // Flags cleared so a modifier the user is still holding cannot widen the delete.
                try makeTaggedKeyPair(from: source, keyCode: Self.deleteKeyCode) { $0.flags = [] }
            }, post: postTaggedKeyPairs)
    }

    public func type(_ text: String) throws(TextInsertionError) {
        guard AXIsProcessTrusted() else { throw .accessibilityDenied }
        guard let source = CGEventSource(stateID: .hidSystemState) else {
            throw .insertionRejected(description: unmakeableKeystroke)
        }
        let keypresses = LayoutKeyCode.keypresses(for: text, stroke: PasteKeyLayout.stroke(for:))
        try buildThenPost(
            keypresses,
            build: { keypress throws(TextInsertionError) in
                switch keypress {
                case .key(let character, let stroke):
                    try makeTaggedKeyPair(from: source, keyCode: stroke.code) { event in
                        // Only layout modifiers are set, so held user modifiers cannot change the character.
                        event.flags = stroke.flags
                        var unit = character
                        event.keyboardSetUnicodeString(stringLength: 1, unicodeString: &unit)
                    }
                case .text(let units):
                    try makeTaggedKeyPair(from: source, keyCode: 0) { event in
                        // Flags cleared so a modifier the user is still holding cannot make this a shortcut.
                        event.flags = []
                        event.keyboardSetUnicodeString(stringLength: units.count, unicodeString: units)
                    }
                }
            }, post: postTaggedKeyPairs)
    }
}

/// The focused text field, found through the Accessibility API; its methods block, so async code calls them via `AccessibilityThread`.
public struct AXAccessibilityFocus: AccessibilityFocus {
    public init() {}

    /// How long one Accessibility message may take, generous because it is the dictation itself.
    private static let messagingTimeout = Float(
        SelectionWriter<AXSelectionAttributes>.messagingTimeout.components.seconds)
    /// Keeps a suggestion read comfortably inside the one-second key hold.
    private static let acceptanceMessagingTimeout: Float = 0.1
    /// Bounds whole-value fallback to fields small enough to copy cheaply.
    private static let smallValueFallbackLimit = 1_024

    /// Anything focused at all, without asking it to report a selection.
    public func hasFocusedElement() -> Bool { focusedElement() != nil }

    public func focusedElementKind() -> FocusedElementKind {
        let element = focusedElement()
        return .of(
            role: element.flatMap { stringAttribute(kAXRoleAttribute, of: $0) }, isPublished: element != nil)
    }

    public func isTrusted() -> Bool { AXIsProcessTrusted() }

    public func isSelfFrontmost() -> Bool {
        NSWorkspace.shared.frontmostApplication?.processIdentifier
            == ProcessInfo.processInfo.processIdentifier
    }

    /// The focused element's owner, which a panel that never activates makes differ from the frontmost. See `Docs/insertion.md`.
    public func focusedApplication() -> InsertionDestination? {
        let frontmost = NSWorkspace.shared.frontmostApplication
        var owner: pid_t = 0
        let focusOwner = focusedElement().flatMap { AXUIElementGetPid($0, &owner) == .success ? owner : nil }
        guard
            let processIdentifier = FocusedElementPreference.destination(
                focusOwner: focusOwner, frontmost: frontmost?.processIdentifier),
            let application = processIdentifier == frontmost?.processIdentifier
                ? frontmost : NSRunningApplication(processIdentifier: processIdentifier)
        else { return nil }
        return InsertionDestination(
            applicationName: application.localizedName,
            bundleIdentifier: application.bundleIdentifier)
    }

    /// Asks the focused element's role and names first, reading the start of its value only when none of them says secure.
    public func focusedFieldIsSecure() -> Bool {
        guard let element = focusedElement() else { return false }
        return isSecureField(element)
    }

    /// The focused field and a bare caret, refusing a secure field and a selection that a write would have collapsed.
    public func focusedFieldPlace() -> FieldPlace? {
        guard let element = focusedElement(), !focusedFieldIsSecure(),
            let range = selectionRange(of: element), range.length == 0
        else { return nil }
        var owner: pid_t = 0
        guard AXUIElementGetPid(element, &owner) == .success else { return nil }
        let field = FieldIdentity(
            processIdentifier: owner, windowNumber: Self.windowNumber(of: element),
            element: Int(bitPattern: CFHash(element)))
        return FieldPlace(field: field, caret: range.location)
    }

    /// The focused element, asked system-wide then per-application, preferring whichever names a text-entry role. See `Docs/insertion.md`.
    private func focusedElement(timeout: Float = Self.messagingTimeout) -> AXUIElement? {
        guard AXIsProcessTrusted() else { return nil }

        // The timeout goes on the element itself: set on the system-wide element it is process-wide, and a suggestion read could lower it mid-insertion (#887).
        let system = AXUIElementCreateSystemWide()
        let systemWide = focusedElement(of: system, timeout: timeout)
        return FocusedElementPreference.choose(
            systemWide: systemWide, systemWideRole: { stringAttribute(kAXRoleAttribute, of: $0) },
            application: {
                guard let frontmost = NSWorkspace.shared.frontmostApplication else { return nil }
                let application = AXUIElementCreateApplication(frontmost.processIdentifier)
                _ = AXUIElementSetMessagingTimeout(application, timeout)
                return focusedElement(of: application, timeout: timeout)
            },
            applicationRole: { stringAttribute(kAXRoleAttribute, of: $0) })
    }

    private func focusedElement(of parent: AXUIElement, timeout: Float) -> AXUIElement? {
        var focused: AnyObject?
        guard
            AXUIElementCopyAttributeValue(
                parent, kAXFocusedUIElementAttribute as CFString, &focused) == .success,
            let element = focused, CFGetTypeID(element) == AXUIElementGetTypeID()
        else { return nil }

        // Checked by type ID above; `as?` on a Core Foundation type always succeeds.
        let field = unsafeDowncast(element, to: AXUIElement.self)
        _ = AXUIElementSetMessagingTimeout(field, timeout)
        return field
    }

    /// The `count` characters before the caret, when the field will report both its value and its caret.
    public func precedingText(_ count: Int) -> String? {
        guard count > 0, let element = focusedElement(),
            let (value, caret) = textBeforeCaret(count, of: element)
        else { return nil }
        return BackwardSelection.text(in: value, endingAt: caret, exactly: count)
    }

    /// As much as the field holds before the caret, so a field shorter than the request is still read.
    public func tail(upTo count: Int) -> FieldTail {
        guard count > 0, let element = focusedElement(),
            let (value, caret) = textBeforeCaret(count, of: element),
            let tail = BackwardSelection.tail(in: value, endingAt: caret, upTo: count)
        else { return .unreadable }
        return .text(tail)
    }

    /// Reads a bounded window where possible, refusing an ambiguous multi-range selection.
    private func textBeforeCaret(_ count: Int, of element: AXUIElement) -> (String, Int)? {
        guard count > 0, !isSecureField(element), let range = selectionRange(of: element) else { return nil }
        var rangeUnavailable = false
        if let window = CaretWindow.before(
            range.location, characters: count,
            ranged: { requested in
                let text = stringForRange(requested, of: element)
                rangeUnavailable = text == nil
                return text
            })
        {
            return (window, window.utf16.count)
        }
        guard rangeUnavailable,
            let length = characterCount(of: element), length <= Self.smallValueFallbackLimit,
            let value = readableValue(of: element)
        else { return nil }
        return (value, range.location)
    }

    /// Reads the window and its text from one AX element, so matching text in another window cannot authorize a write.
    public func windowNumberAndTail(upTo count: Int) -> (windowNumber: UInt32?, tail: FieldTail) {
        guard count > 0, let element = focusedElement() else { return (nil, .unreadable) }
        let number = Self.windowNumber(of: element)
        guard let (value, caret) = textBeforeCaret(count, of: element),
            let tail = BackwardSelection.tail(in: value, endingAt: caret, upTo: count)
        else { return (number, .unreadable) }
        return (number, .text(tail))
    }

    /// Reads an accepted suggestion's tail with a short per-element timeout.
    public func acceptanceWindowNumberAndTail(upTo count: Int) -> (windowNumber: UInt32?, tail: FieldTail) {
        guard count > 0,
            let element = focusedElement(timeout: Self.acceptanceMessagingTimeout)
        else { return (nil, .unreadable) }
        let number = Self.windowNumber(of: element)
        guard let (value, caret) = textBeforeCaret(count, of: element),
            let tail = BackwardSelection.tail(in: value, endingAt: caret, upTo: count)
        else { return (number, .unreadable) }
        return (number, .text(tail))
    }

    /// Rechecks the destination window with the short accept-path timeout.
    public func acceptanceFocusedWindowNumber() -> UInt32? {
        focusedElement(timeout: Self.acceptanceMessagingTimeout).flatMap(Self.windowNumber(of:))
    }

    /// The window containing this focused field, or nothing when the system cannot identify it.
    private static func windowNumber(of element: AXUIElement) -> UInt32? {
        var number: CGWindowID = 0
        guard axUIElementGetWindow(element, &number) == .success else { return nil }
        return number
    }

    /// The window containing the field currently focused for insertion.
    public func focusedWindowNumber() -> UInt32? {
        focusedElement().flatMap(Self.windowNumber(of:))
    }

    public func focusedTextField() -> (any FocusedTextField)? {
        guard let candidate = focusedElement(), acceptsSingleSelection(candidate) else { return nil }
        return SelectionWriter(field: AXSelectionAttributes(element: candidate))
    }

    public func focusedTextField(in destination: InsertionDestination) -> (any FocusedTextField)? {
        guard let bundleIdentifier = destination.bundleIdentifier,
            focusedApplication()?.bundleIdentifier == bundleIdentifier,
            let candidate = focusedElement()
        else { return nil }
        var processIdentifier: pid_t = 0
        guard AXUIElementGetPid(candidate, &processIdentifier) == .success,
            NSRunningApplication(processIdentifier: processIdentifier)?.bundleIdentifier == bundleIdentifier,
            acceptsSingleSelection(candidate)
        else { return nil }
        return SelectionWriter(field: AXSelectionAttributes(element: candidate))
    }

    /// Rejects ambiguous multi-caret selections and fields that cannot accept text writes.
    private func acceptsSingleSelection(_ candidate: AXUIElement) -> Bool {
        guard case .discontinuous = selection(of: candidate) else {
            return FocusedTextFieldEligibility.accepts(
                role: stringAttribute(kAXRoleAttribute, of: candidate),
                selectedTextIsReadable: {
                    var selection: AnyObject?
                    return AXUIElementCopyAttributeValue(
                        candidate, kAXSelectedTextAttribute as CFString, &selection) == .success
                },
                selectedTextIsSettable: {
                    var settable = DarwinBoolean(false)
                    return AXUIElementIsAttributeSettable(
                        candidate, kAXSelectedTextAttribute as CFString, &settable) == .success
                        && settable.boolValue
                })
        }
        return false
    }
}

/// Confirms the focused element is a writable text control before exposing it to insertion.
enum FocusedTextFieldEligibility {
    /// A readable selection alone does not establish that the element accepts text writes.
    static func accepts(
        role: String?, selectedTextIsReadable: () -> Bool, selectedTextIsSettable: () -> Bool
    ) -> Bool {
        FocusedElementPreference.isTextEntry(role)
            && selectedTextIsReadable()
            && selectedTextIsSettable()
    }
}

/// A focused field's selection attributes, holding an `AXUIElement` that is safe to pass between threads.
private struct AXSelectionAttributes: SelectionAttributes, @unchecked Sendable {
    /// The focused element this reads and writes.
    let element: AXUIElement

    func value() -> String? {
        readableValue(of: element)
    }

    func selectedRange() -> CFRange? {
        selectionRange(of: element)
    }

    func length() -> Int? {
        characterCount(of: element)
    }

    func text(in range: Range<Int>) -> String? {
        guard !isSecureField(element) else { return nil }
        return stringForRange(range, of: element)
    }

    func setSelectedText(_ text: String) -> AXError {
        guard attributeIsSettable(kAXSelectedTextAttribute as CFString, on: element) else {
            return .attributeUnsupported
        }
        return AXUIElementSetAttributeValue(
            element, kAXSelectedTextAttribute as CFString, text as CFString)
    }

    /// A range that cannot be described is reported as an illegal argument, which the writer refuses.
    func setSelectedRange(_ range: CFRange) -> AXError {
        guard attributeIsSettable(kAXSelectedTextRangeAttribute as CFString, on: element) else {
            return .attributeUnsupported
        }
        var range = range
        guard let value = AXValueCreate(.cfRange, &range) else { return .illegalArgument }
        return AXUIElementSetAttributeValue(element, kAXSelectedTextRangeAttribute as CFString, value)
    }
}

/// Returns whether the Accessibility server confirms an attribute accepts writes.
private func attributeIsSettable(_ attribute: CFString, on element: AXUIElement) -> Bool {
    var settable = DarwinBoolean(false)
    return AXUIElementIsAttributeSettable(element, attribute, &settable) == .success
        && settable.boolValue
}

/// The element's value through the shared field reader, or `nil` for a secure field, whose value is never asked for.
private func readableValue(of element: AXUIElement) -> String? {
    SurfaceProbe.readableValue(of: element)
}

/// The shared secure-check order: the field's names first, a bounded prefix of its value only when they clear it.
private func isSecureField(_ element: AXUIElement) -> Bool {
    SurfaceProbe.names(of: element).isSecure(value: {
        CaretWindow.prefix(length: characterCount(of: element), ranged: { stringForRange($0, of: element) })
    })
}

/// The string an Accessibility attribute holds, or `nil` when the element will not say.
private func stringAttribute(_ name: String, of element: AXUIElement) -> String? {
    var current: AnyObject?
    guard
        AXUIElementCopyAttributeValue(element, name as CFString, &current) == .success
    else { return nil }
    return current as? String
}

/// The text a UTF-16 range of the element covers, or `nil` when it will not read by range.
private func stringForRange(_ range: Range<Int>, of element: AXUIElement) -> String? {
    var cfRange = CFRange(location: range.lowerBound, length: range.count)
    guard let parameter = AXValueCreate(.cfRange, &cfRange) else { return nil }
    var current: AnyObject?
    guard
        AXUIElementCopyParameterizedAttributeValue(
            element, kAXStringForRangeParameterizedAttribute as CFString, parameter, &current)
            == .success
    else { return nil }
    return current as? String
}

/// The element's length in UTF-16 units, or `nil` when it will not say.
private func characterCount(of element: AXUIElement) -> Int? {
    var current: AnyObject?
    guard
        AXUIElementCopyAttributeValue(
            element, kAXNumberOfCharactersAttribute as CFString, &current) == .success
    else { return nil }
    return (current as? NSNumber)?.intValue
}

/// The range an Accessibility attribute holds, or `nil` when the element will not say.
private func rangeAttribute(_ name: String, of element: AXUIElement) -> CFRange? {
    var current: AnyObject?
    guard
        AXUIElementCopyAttributeValue(element, name as CFString, &current) == .success,
        let value = current, CFGetTypeID(value) == AXValueGetTypeID()
    else { return nil }

    // Checked by type ID above; `as?` on a Core Foundation type always succeeds.
    var range = CFRange()
    guard AXValueGetValue(unsafeDowncast(value, to: AXValue.self), .cfRange, &range) else {
        return nil
    }
    return range
}

/// The focused field's single usable selection, or nothing when it reports multiple ranges.
private func selectionRange(of element: AXUIElement) -> CFRange? {
    if case .range(let range) = selection(of: element) { return range }
    return nil
}

/// Reads plural selections before the singular attribute, which can be stale for multi-cursor fields.
private func selection(of element: AXUIElement) -> AccessibilitySelection {
    var plural: AnyObject?
    let pluralResult = AXUIElementCopyAttributeValue(
        element, kAXSelectedTextRangesAttribute as CFString, &plural)
    if pluralResult == .success, let values = plural as? [AnyObject], values.count > 1 {
        return .discontinuous
    }
    let pluralRanges = (plural as? [AnyObject])?.compactMap { rangeValue($0) }
    return AccessibilitySelection.resolve(
        singular: rangeAttribute(kAXSelectedTextRangeAttribute, of: element), plural: pluralRanges,
        textLength: characterCount(of: element))
}

/// Unwraps one Accessibility value as a character range.
private func rangeValue(_ value: AnyObject) -> CFRange? {
    guard CFGetTypeID(value) == AXValueGetTypeID() else { return nil }
    var range = CFRange()
    guard AXValueGetValue(unsafeDowncast(value, to: AXValue.self), .cfRange, &range) else {
        return nil
    }
    return range
}

/// Posts a keystroke the tap took and the session refused, tagged so neither the tap nor the monitor takes it again.
public enum KeyStrokeReturn {
    /// Presses the stroke's key with its modifiers in the focused application.
    public static func post(_ stroke: UttrflowPredict.KeyStroke) {
        guard let keyCode = stroke.key.keyCode,
            let source = CGEventSource(stateID: .hidSystemState)
        else { return }
        var flags = CGEventFlags()
        if stroke.modifiers.contains(.command) { flags.insert(.maskCommand) }
        if stroke.modifiers.contains(.option) { flags.insert(.maskAlternate) }
        if stroke.modifiers.contains(.control) { flags.insert(.maskControl) }
        if stroke.modifiers.contains(.shift) { flags.insert(.maskShift) }
        try? postTaggedKeyPair(from: source, keyCode: CGKeyCode(keyCode)) { $0.flags = flags }
    }
}
