// Tests for honouring what a password manager says about its copy.

import Foundation
import Testing
import UttrflowCore

@testable import UttrflowClipboard

@Suite("A password manager's copy is hidden or not kept")
struct PasteboardMarkersTests {
    @Test("reads the three nspasteboard.org markers and ignores every other type")
    func readsTheMarkers() {
        let markers = PasteboardMarkers(types: [
            "public.utf8-plain-text", "org.nspasteboard.ConcealedType",
            "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType",
            "org.nspasteboard.source",
        ])
        #expect(markers == [.concealed, .transient, .autoGenerated])
        #expect(PasteboardMarkers(types: ["public.utf8-plain-text", "public.html"]).isEmpty)
    }

    @Test("records a concealed copy and refuses a transient or generated one")
    func whatMayBeRecorded() {
        #expect(PasteboardMarkers().allowsRecording)
        #expect(PasteboardMarkers.concealed.allowsRecording)
        #expect(!PasteboardMarkers.transient.allowsRecording)
        #expect(!PasteboardMarkers.autoGenerated.allowsRecording)
        #expect(!PasteboardMarkers([.concealed, .transient]).allowsRecording)
    }

    /// Ordinary passwords have no shape, so the marker is what hides them.
    @Test(
        "hides a concealed copy whatever it looks like",
        arguments: ["hunter2", "Tr0ub4dor&3", "P@ssw0rd!2024", "correct horse battery staple"])
    func concealedIsSecret(_ password: String) async {
        let clipboard = FakeClipboard()
        let watcher = PasteboardWatcher(source: clipboard, now: { noon })
        clipboard.write(password, from: "Passwords", marked: .concealed)

        let clip = await watcher.newClip(at: noon)?.clip

        #expect(clip?.text == password)
        #expect(clip?.kind == .secret)
        #expect(clipboard.contentReads == 1)
    }

    /// Without the marker the same words are text: the promise covers password managers, not passwords.
    @Test("leaves an unmarked short password as text")
    func unmarkedPasswordIsText() async {
        let clipboard = FakeClipboard()
        let watcher = PasteboardWatcher(source: clipboard, now: { noon })
        clipboard.write("Tr0ub4dor&3", from: "Notes")

        #expect(await watcher.newClip(at: noon)?.clip.kind == .text)
    }

    /// A password must never be paired with the markers of the ordinary copy that replaced it.
    @Test("rereads a copy that changed while its markers were read")
    func writeBetweenReads() async {
        let clipboard = FakeClipboard()
        let watcher = PasteboardWatcher(source: clipboard, now: { noon })
        clipboard.write("Tr0ub4dor&3", from: "Passwords", marked: .concealed)
        clipboard.writeWhileMarkersAreRead("hello")

        #expect(await watcher.newClip(at: noon) == nil)
        #expect(clipboard.contentReads == 0)
        let next = await watcher.newClip(at: noon)?.clip
        #expect(next?.text == "hello")
        #expect(next?.kind == .text)
        #expect(clipboard.contentReads == 1)
    }

    @Test(
        "does not record a transient or generated copy",
        arguments: [
            PasteboardMarkers.transient, .autoGenerated, [.concealed, .transient],
        ])
    func notRecorded(_ markers: PasteboardMarkers) async {
        let clipboard = FakeClipboard()
        let watcher = PasteboardWatcher(source: clipboard, now: { noon })
        clipboard.write("Tr0ub4dor&3", from: "Passwords", marked: markers)
        #expect(await watcher.newClip(at: noon) == nil)
        #expect(clipboard.contentReads == 0)

        let picture = (data: Data([0x89, 0x50]), width: 1, height: 1)
        clipboard.write(nil, picture: picture, marked: markers)
        #expect(await watcher.newClip(at: noon) == nil)
        #expect(clipboard.contentReads == 0)

        // The next ordinary copy is still noticed.
        clipboard.write("hello")
        #expect(await watcher.newClip(at: noon)?.clip.text == "hello")
        #expect(clipboard.contentReads == 1)
    }
}
