import Testing
@testable import UttrflowCore

@testable import UttrflowAI

/// Generated letter runs whose written form is pinned, so a change to how runs are read shows here first.
@Suite("SpelledInitialismPass letter runs")
struct LetterRunPropertyTests {
    private static let letters = [
        "a", "b", "c", "e", "g", "i", "k", "m", "s", "oh", "you", "see", "ex", "dee",
    ]
    private static let neighbours = ["", "a", "i", "oh", "5", "and", "need", "the", "seven"]

    /// 300 runs of one to six letter names, each with a fixed-seed neighbour before and after.
    static func generatedRuns() -> [String] {
        var state: UInt64 = 0x5EED
        func next(_ bound: Int) -> Int {
            state = state &* 6_364_136_223_846_793_005 &+ 1_442_695_040_888_963_407
            return Int((state >> 33) % UInt64(bound))
        }
        return (0..<300).map { index in
            let run = (0...(index % 6)).map { _ in letters[next(letters.count)] }
            let words = [neighbours[next(neighbours.count)]] + run + [neighbours[next(neighbours.count)]]
            return words.filter { !$0.isEmpty }.joined(separator: " ")
        }
    }

    @Test("every generated run is written as pinned")
    func pinned() {
        let runs = Self.generatedRuns()
        #expect(runs == Self.pinnedRuns.map(\.0))
        for (run, pinned) in zip(runs, Self.pinnedRuns) {
            #expect(SpelledInitialismPass().apply(Draft(text: run)).text == pinned.1, "\(run)")
        }
    }

    @Test(
        "each kind of run is written by its row",
        arguments: [
            (["A", "P", "I"], LetterRun.Kind.initialism, "a", "API"),
            (["E", "G"], .dottedPair, "e", "e.g."),
            (["M", "G"], .unitSymbol, "m", "mg"),
        ])
    func writers(letters: [String], kind: LetterRun.Kind, first: String, expected: String) {
        #expect(LetterRun.written(letters, as: kind, first: first) == expected)
    }

    @Test("every kind has a writer")
    func everyKindWritten() {
        #expect(LetterRun.Kind.allCases.allSatisfy { LetterRun.writers[$0] != nil })
    }

    /// Each generated run and the text the pass writes for it.
    static let pinnedRuns: [(String, String)] = [
        ("a the", "a the"),
        ("i m c a", "IMCA"),
        ("a ex g see 5", "AXG see 5"),
        ("i i i you see need", "III you see need"),
        ("i a dee i c see and", "IADIC see and"),
        ("i g m see dee dee a i", "IGM see DDAI"),
        ("i b and", "IB and"),
        ("5 g dee seven", "5 g dee seven"),
        ("a dee you ex 5", "a dee you ex 5"),
        ("need k b e e 5", "need KBEE5"),
        ("5 b see i k c oh", "5 BCIKCO"),
        ("and you m i ex see c the", "and you MIX see c the"),
        ("oh i a", "oh IA"),
        ("seven you you and", "seven you you and"),
        ("i e oh i a", "IEOIA"),
        ("a g ex e m oh", "AGXEMO"),
        ("the a i b a i and", "the AIBAI and"),
        ("and b a b a c b the", "and BABACB the"),
        ("and see need", "and see need"),
        ("the c k the", "the CK the"),
        ("and a a i oh", "and AAIO"),
        ("and ex oh m k and", "and ex oh MK and"),
        ("the i e see c a need", "the IECC a need"),
        ("the m dee a m dee i and", "the MDAMDI and"),
        ("5 e", "5 e"),
        ("a e c i", "AECI"),
        ("oh see e oh need", "oh see e oh need"),
        ("oh oh b you b a", "oh oh BUBA"),
        ("and m dee see k e the", "and m dee see KE the"),
        ("oh m s k see b e oh", "oh MSKCBEO"),
        ("need a need", "need a need"),
        ("5 c a the", "5 c a the"),
        ("k ex a a", "k ex a a"),
        ("a b you a i 5", "a b you AI5"),
        ("the you s a you a oh", "the you SAUAO"),
        ("a k b oh ex see k 5", "AKB oh ex see k 5"),
        ("a i 5", "AI5"),
        ("oh k k and", "oh KK and"),
        ("i a dee", "IAD"),
        ("and c see a g", "and CCAG"),
        ("a ex b m a s oh", "a ex BMASO"),
        ("the dee c k a b b a", "the DCKABBA"),
        ("the you the", "the you the"),
        ("and g a a", "and GAA"),
        ("i you k g seven", "IUKG seven"),
        ("need b e c ex oh", "need BECX oh"),
        ("a you g s k i 5", "AUGSKI5"),
        ("and i see g oh dee k oh", "and ICG oh DKO"),
        ("dee seven", "dee seven"),
        ("5 g k seven", "5 GK seven"),
        ("i b b oh 5", "IBB oh 5"),
        ("and dee m dee a 5", "and DMDA5"),
        ("the b oh oh dee a i", "the b oh oh DAI"),
        ("the c b i e m oh a", "the CBIEMOA"),
        ("need oh i", "need oh i"),
        ("and e dee need", "and e dee need"),
        ("and a s k oh", "and ASKO"),
        ("oh g a e e a", "oh GAEEA"),
        ("oh dee s you oh c a", "oh dee s you oh CA"),
        ("e e see c k k oh", "EECCKKO"),
        ("the k 5", "the k 5"),
        ("5 ex see a", "5 ex see a"),
        ("i ex b s the", "IXBS the"),
        ("and c see b you 5", "and CCB you 5"),
        ("seven you s m dee ex need", "seven you SMDX need"),
        ("seven see s i s see oh i", "seven see SIS see oh i"),
        ("a k oh", "AKO"),
        ("i a b a", "IABA"),
        ("seven see oh you 5", "seven see oh you 5"),
        ("need a ex i k", "need AXIK"),
        ("seven you i oh you b 5", "seven you i oh you b 5"),
        ("need m m dee k you b oh", "need MMDKUBO"),
        ("ex 5", "ex 5"),
        ("the s you i", "the SUI"),
        ("5 e oh b and", "5 EOB and"),
        ("a i i g see 5", "AIIG see 5"),
        ("the ex m b s k", "the XMBSK"),
        ("the g oh m i oh see a", "the GOMI oh see a"),
        ("and oh oh", "and oh oh"),
        ("need e you need", "need e you need"),
        ("need m k e and", "need MKE and"),
        ("seven k a m e the", "seven KAME the"),
        ("and i ex g dee m the", "and IXGDM the"),
        ("5 a i c g m i oh", "5 AICGMIO"),
        ("and ex oh", "and ex oh"),
        ("i see a 5", "i see a 5"),
        ("the g s c seven", "the GSC seven"),
        ("the e e e c i", "the EEECI"),
        ("and k dee a k i the", "and KDAKI the"),
        ("oh you g c you c m oh", "oh you GCUCMO"),
        ("and you 5", "and you 5"),
        ("and m m oh", "and MMO"),
        ("seven s oh oh a", "seven s oh oh a"),
        ("the ex i oh m oh", "the XIOMO"),
        ("i b k oh dee the", "IBK oh dee the"),
        ("need b a s oh you a i", "need BAS oh you a i"),
        ("i see seven", "i see seven"),
        ("5 oh ex a", "5 oh ex a"),
        ("seven you s see oh", "seven you s see oh"),
        ("need k e a a the", "need KEAA the"),
        ("a m k i oh k seven", "AMKIOK seven"),
        ("oh dee e e c g a a", "oh DEECGAA"),
        ("and s 5", "and s 5"),
        ("a you a seven", "a you a seven"),
        ("need a ex see 5", "need a ex see 5"),
        ("seven ex s s you and", "seven XSS you and"),
        ("seven e dee s m c the", "seven EDSMC the"),
        ("a ex see a i g i need", "a ex see AIGI need"),
        ("and b need", "and b need"),
        ("5 e dee need", "5 e dee need"),
        ("e ex i i", "EXII"),
        ("the g ex g i oh", "the GXGIO"),
        ("you dee g dee you and", "you DGD you and"),
        ("oh i you s s you s i", "oh IUSSUSI"),
        ("seven a i", "seven AI"),
        ("seven b b the", "seven BB the"),
        ("seven ex b dee need", "seven XBD need"),
        ("oh you ex dee c", "oh you XDC"),
        ("m e i you g and", "MEIUG and"),
        ("oh oh you e b c ex 5", "oh oh you EBCX5"),
        ("e the", "e the"),
        ("i g k 5", "IGK5"),
        ("5 c e see", "5 CEC"),
        ("seven e c oh dee need", "seven EC oh dee need"),
        ("oh s dee you you and", "oh s dee you you and"),
        ("i c see s m see e 5", "ICCSMCE5"),
        ("the s", "the s"),
        ("the ex e", "the ex e"),
        ("and i m i a", "and IMIA"),
        ("you b s dee seven", "you BSD seven"),
        ("seven oh e c i oh 5", "seven oh ECI oh 5"),
        ("a oh k a oh dee m", "a oh KA oh dee m"),
        ("oh g and", "oh g and"),
        ("c ex 5", "c ex 5"),
        ("need k i e seven", "need KIE seven"),
        ("a oh i b a", "a oh IBA"),
        ("c e b m ex a", "CEBMXA"),
        ("5 dee e i ex k m i", "5 DEIXKMI"),
        ("i g and", "IG and"),
        ("s a oh", "SAO"),
        ("seven ex you oh i", "seven ex you oh i"),
        ("the s i see b the", "the SICB the"),
        ("b i oh k i 5", "BIOKI5"),
        ("need a oh m s g m", "need AOMSGM"),
        ("5 s need", "5 s need"),
        ("seven dee dee the", "seven dee dee the"),
        ("i dee g e a", "IDGEA"),
        ("i ex c i ex a", "IXCIXA"),
        ("a e see c a b a", "a e see CABA"),
        ("i oh a ex ex you c a", "IOAXX you CA"),
        ("seven c the", "seven c the"),
        ("i s e need", "ISE need"),
        ("the i oh s the", "the IOS the"),
        ("i see you dee and", "i see you dee and"),
        ("a b c i oh you seven", "ABCI oh you seven"),
        ("seven b g oh b c a a", "seven BGOBCAA"),
        ("seven k the", "seven k the"),
        ("the ex c", "the ex c"),
        ("i e k i the", "IEKI the"),
        ("seven k s i b seven", "seven KSIB seven"),
        ("need c k k m ex the", "need CKKMX the"),
        ("seven s you ex b ex ex and", "seven s you XBXX and"),
        ("oh ex and", "oh ex and"),
        ("seven dee k a", "seven DKA"),
        ("5 m k ex a", "5 MKXA"),
        ("need g i i see need", "need GII see need"),
        ("oh c dee oh g k a", "oh c dee oh GKA"),
        ("and k ex ex e dee oh i", "and KXXED oh i"),
        ("oh e i", "oh EI"),
        ("oh see s", "oh see s"),
        ("and e i see 5", "and EI see 5"),
        ("a i s ex b need", "AISXB need"),
        ("and e oh b k i a", "and EOBKIA"),
        ("the c s b b b e need", "the CSBBBE need"),
        ("and oh seven", "and oh seven"),
        ("need k s i", "need KSI"),
        ("i c g c 5", "ICGC5"),
        ("and g b i dee oh", "and GBID oh"),
        ("i k k you see c oh", "IKK you see c oh"),
        ("seven m dee k you dee dee", "seven MDK you dee dee"),
        ("g need", "g need"),
        ("seven e e a", "seven EEA"),
        ("and m s b 5", "and MSB5"),
        ("need s ex dee see seven", "need SXD see seven"),
        ("a b m k e k", "ABMKEK"),
        ("need ex s c ex see s need", "need XSCX see s need"),
        ("5 c 5", "5 c 5"),
        ("a s s and", "ASS and"),
        ("oh see s k i", "oh see SKI"),
        ("5 m dee e i the", "5 MDEI the"),
        ("seven you b oh you c", "seven you b oh you c"),
        ("and e i you you g s seven", "and EI you you GS seven"),
        ("oh a need", "oh a need"),
        ("a c c need", "ACC need"),
        ("need g see b need", "need GCB need"),
        ("seven c you ex oh", "seven c you ex oh"),
        ("5 you c dee you dee i", "5 you c dee you dee i"),
        ("c a m dee see s", "CAMD see s"),
        ("oh ex the", "oh ex the"),
        ("the a dee i", "the ADI"),
        ("oh a e b the", "oh AEB the"),
        ("need ex ex e k seven", "need XXEK seven"),
        ("5 e ex see g e the", "5 e ex see GE the"),
        ("you i k ex g you", "you IKXGU"),
        ("need g the", "need g the"),
        ("oh c g the", "oh CG the"),
        ("the e ex c 5", "the EXC5"),
        ("need m s oh m 5", "need MSOM5"),
        ("the b k a a e and", "the BKAAE and"),
        ("seven a see c e see dee", "seven ACCE see dee"),
        ("seven m the", "seven m the"),
        ("seven b e oh", "seven BEO"),
        ("and k oh b a", "and KOBA"),
        ("seven m dee oh you i", "seven m dee oh you i"),
        ("i m b c m 5", "IMBCM5"),
        ("seven s dee g see i you 5", "seven SDGCI you 5"),
        ("k seven", "k seven"),
        ("the see see need", "the see see need"),
        ("the dee dee dee seven", "the DDD seven"),
        ("5 k m c b oh", "5 KMCBO"),
        ("a a i oh g k the", "AAIOGK the"),
        ("the g ex i you oh i a", "the GXI you oh IA"),
        ("oh m seven", "oh m seven"),
        ("and oh a the", "and oh a the"),
        ("seven ex c s oh", "seven XCSO"),
        ("need m b g c the", "need MBGC the"),
        ("oh g i i ex oh seven", "oh GIIX oh seven"),
        ("seven e c g you i s oh", "seven ECGUISO"),
        ("need see need", "need see need"),
        ("5 c b", "5 CB"),
        ("ex see s the", "ex see s the"),
        ("seven m dee k g oh", "seven MDKGO"),
        ("5 oh see oh oh c 5", "5 oh see oh oh c 5"),
        ("i e ex g ex m oh 5", "IEXGXM oh 5"),
        ("m 5", "m 5"),
        ("the b dee seven", "the b dee seven"),
        ("i a oh you oh", "IA oh you oh"),
        ("5 ex dee oh b need", "5 ex dee oh b need"),
        ("a a see i you s i", "a ACIUSI"),
        ("5 k a ex e b s the", "5 KAXEBS the"),
        ("i oh and", "i oh and"),
        ("seven oh s and", "seven oh s and"),
        ("seven m b g and", "seven MBG and"),
        ("need i see a a oh", "need i see a a oh"),
        ("seven you you b c k 5", "seven you you BCK5"),
        ("a see a you s i k seven", "a see AUSIK seven"),
        ("the k the", "the k the"),
        ("s ex and", "s ex and"),
        ("i k e s", "IKES"),
        ("seven g ex b dee need", "seven GXBD need"),
        ("seven b dee e c s need", "seven BDECS need"),
        ("i you b oh i you dee and", "IUBOI you dee and"),
        ("the s i", "the SI"),
        ("oh s g 5", "oh SG5"),
        ("seven ex c k a", "seven XCKA"),
        ("i you see see you i", "i you see see you i"),
        ("seven dee s c dee b i", "seven DSCDBI"),
        ("and a s oh c b s oh", "and ASOCBSO"),
        ("need see 5", "need see 5"),
        ("5 c g", "5 CG"),
        ("i i k see seven", "IIK see seven"),
        ("i you oh g k the", "i you oh GK the"),
        ("oh e s e i a and", "oh ESEI a and"),
        ("oh ex see b oh e b 5", "oh ex see BOEB5"),
        ("seven k a", "seven KA"),
        ("oh b c i", "oh BCI"),
        ("and m e m oh", "and MEMO"),
        ("5 dee c c oh i", "5 DCCOI"),
        ("and m b m m e i", "and MBMMEI"),
        ("and dee you dee you e b and", "and dee you dee you EB and"),
        ("and dee", "and dee"),
        ("a you dee seven", "a you dee seven"),
        ("i oh a ex the", "IOAX the"),
        ("need s oh a a and", "need s oh a a and"),
        ("you oh dee g ex", "you oh DGX"),
        ("5 see e e i e oh oh", "5 see EEIE oh oh"),
        ("g need", "g need"),
        ("i ex s oh", "IXSO"),
        ("and g c you and", "and GC you and"),
        ("5 g see g i a", "5 GCGIA"),
        ("need you c b g dee the", "need you CBGD the"),
        ("need oh i see ex s s 5", "need oh i see XSS5"),
        ("i a", "IA"),
        ("5 e m oh", "5 EMO"),
        ("i c see c a", "ICCCA"),
        ("k g a g i", "KGAGI"),
        ("a a k m see k i", "AAKMCKI"),
        ("i oh ex g g s i and", "i oh XGGSI and"),
        ("5 b a", "5 BA"),
        ("the s e a", "the SEA"),
        ("5 k s m a", "5 KSMA"),
        ("e e g s 5", "EEGS5"),
        ("oh you k s s b oh", "oh you KSSBO"),
        ("5 m b oh b ex see i", "5 MBOBX see i"),
        ("you seven", "you seven"),
        ("the s ex oh", "the s ex oh"),
        ("a c g dee a", "a c GDA"),
        ("oh i g oh you oh", "oh IG oh you oh"),
        ("oh oh dee b dee you the", "oh oh DBD you the"),
        ("need b g e see s i the", "need BGECSI the"),
    ]
}
