import AppKit
import Foundation
import Synchronization
import Testing
import UttrflowCore

@testable import UttrflowInput

@Suite("Dictation pasteboard markers")
struct PasteboardMarkerWriteTests {
    @Test("puts the transient marker beside the same text and rich text item")
    func transientMarkerSharesThePasteboardItem() {
        let item = SystemPasteboard.textItem(
            "dictated words", richText: "<b>dictated words</b>",
            marker: .transient)

        #expect(item.string(forType: .string) == "dictated words")
        #expect(item.string(forType: .html) == "<b>dictated words</b>")
        #expect(item.types.contains(NSPasteboard.PasteboardType("org.nspasteboard.TransientType")))
    }

    @Test("puts the generated marker beside clipboard-floor text")
    func generatedMarkerSharesThePasteboardItem() {
        let item = SystemPasteboard.textItem(
            "dictated words", richText: nil,
            marker: .autoGenerated)

        #expect(item.string(forType: .string) == "dictated words")
        #expect(item.types.contains(NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")))
    }

    @Test("leaves ordinary user copies unmarked")
    func ordinaryCopyHasNoMarker() {
        let item = SystemPasteboard.textItem("user copied words", richText: nil)

        #expect(item.string(forType: .string) == "user copied words")
        #expect(!item.types.contains { $0.rawValue.hasPrefix("org.nspasteboard.") })
    }

    @Test("accepts text beginning with a byte-order mark on a named pasteboard")
    @MainActor
    func leadingByteOrderMarkIsWritten() {
        let pasteboard = NSPasteboard(name: .init("com.uttrflow.tests.\(UUID().uuidString)"))
        defer { pasteboard.releaseGlobally() }
        pasteboard.clearContents()
        let announced = Mutex<String?>(nil)
        let systemPasteboard = SystemPasteboard(willWrite: { text in
            announced.withLock { $0 = text }
            return { _ in }
        })

        let result = systemPasteboard.writeText("\u{FEFF}hi", richText: nil, to: pasteboard)

        #expect(result.didWrite)
        #expect(result.changeCount == pasteboard.changeCount)
        #expect(announced.withLock { $0 } == "\u{FEFF}hi")
        let readback = pasteboard.string(forType: .string)
        let submitted = announced.withLock { $0 } ?? ""
        #expect(InsertionPasteboardReadback.matches(readback, for: submitted))
        #expect(!InsertionPasteboardReadback.matches(readback, for: "different text"))
        #expect(InsertionPasteboardReadback.matches("hello", for: "hello"))
        #expect(InsertionPasteboardReadback.matches("hello", for: "\u{FEFF}hello"))
        #expect(!InsertionPasteboardReadback.matches(nil, for: "hello"))
        #expect(!InsertionPasteboardReadback.matches("hello", for: "\u{FEFF}\u{FEFF}hello"))
        #expect(!InsertionPasteboardReadback.matches("hello", for: "hello\u{FEFF}"))
        #expect(!InsertionPasteboardReadback.matches("é", for: "e\u{0301}"))
    }
}
