// The nspasteboard.org markers a writer puts beside what it copies.

/// What a copy's writer says about it, by the nspasteboard.org convention. See Docs/clipboard-secrets.md.
public struct PasteboardMarkers: OptionSet, Sendable, Hashable {
    public let rawValue: Int

    public init(rawValue: Int) { self.rawValue = rawValue }

    /// A password or similar, whose safe handling depends on the copied flavour.
    public static let concealed = PasteboardMarkers(rawValue: 1 << 0)
    /// A copy made to move data somewhere, never meant for a history.
    public static let transient = PasteboardMarkers(rawValue: 1 << 1)
    /// Contents written by software rather than copied by a person.
    public static let autoGenerated = PasteboardMarkers(rawValue: 1 << 2)

    /// Each type a reader recognises and its marker; only the convention's own types are ever written.
    private static let types: [(marker: PasteboardMarkers, type: String, written: Bool)] = [
        (.concealed, "org.nspasteboard.ConcealedType", true),
        (.transient, "org.nspasteboard.TransientType", true),
        (.autoGenerated, "org.nspasteboard.AutoGeneratedType", true),
        (.transient, "de.petermaurer.TransientPasteboardType", false),
        (.concealed, "com.agilebits.onepassword", false),
        (.transient, "com.typeit4me.clipping", false),
        (.transient, "Pasteboard generator type", false),
    ]

    /// The markers named among a clipboard's type identifiers; every other type is ignored.
    public init(types: [String]) {
        self = Self.types.reduce(into: []) { markers, entry in
            if types.contains(entry.type) { markers.insert(entry.marker) }
        }
    }

    /// The pasteboard type identifiers a writer adds to carry these markers.
    public var typeIdentifiers: [String] {
        Self.types.filter { $0.written && contains($0.marker) }.map(\.type)
    }

    /// Whether a history may record the copy at all; concealed is decided after reading the flavour.
    public var allowsRecording: Bool { isDisjoint(with: [.transient, .autoGenerated]) }
}
